### ISSUE TITLE
Missing mime deps

### ISSUE THREAD

**Issue by solisoft** [werner/amatista#5]
I'm testing the framework and I have an issue.

In the doc you say to set Project file like that : 

```
deps do
  github "werner/amatista"
end
```

So I did it, ran "crystal deps" and then I copied/paste your sample into test.rc

Here the error : 
crystal test.cr
Error in ./test.cr:1: while requiring "amatista"

require "amatista"
^

in ./libs/amatista/amatista.cr:1: while requiring "./amatista/**"

require "./amatista/**"
^

in ./libs/amatista/amatista/controller.cr:1: while requiring "./helpers"

require "./helpers"
^

in ./libs/amatista/amatista/helpers.cr:1: while requiring "mime": can't find file 'mime' relative to '/Users/olivier/workspace/a_test/libs/amatista/amatista'

require "mime"

**Comment by werner** [comment]
Yes, you're right, there's no a dependency manager in Crystal yet, so I just updated the Readme to reflect that.

Thanks for the testing. :)
