### ISSUE TITLE
App crash but compile fine

### ISSUE THREAD

**Issue by solisoft** [werner/amatista#6]
Hi again, 

Running a simple : crystal test.cr (where test.cr is just the basic sample just crash) but running : crystal build test.cr --release works fine

here the error log : (I use crystal 0.7.6 on my mac)
crystal test.cr
Undefined symbols for architecture x86_64:
  "_*Main::new:Main", referenced from:
      ___crystal_main in main.o
      ___crystal_main in Main.o
  "__Main@Amatista::Base#process_request<Main, HTTP::Request>:HTTP::Response", referenced from:
      _~fun_literal_16 in main.o
      _~fun_literal_16 in Main.o
  "__Main@Amatista::Base#process_static<Main, String>:HTTP::Response?", referenced from:
      _~fun_literal_16 in main.o
      _~fun_literal_16 in Main.o
  "_*Main@Amatista::Base#run<Main, Int32>:Nil", referenced from:
      ___crystal_main in main.o
      ___crystal_main in Main.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: execution of command failed with code: 1: `cc -o /Users/olivier/workspace/a_test/.crystal/crystal-run-test.tmp "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/main.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/StaticArray40Int8443225641.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Pointer40Int841.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Array40Int3241.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/String5858Builder.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/GC.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/String.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Slice40T41.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Slice40UInt841.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Math.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Pointer40UInt841.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/IndexError.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/ArgumentError.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Pointer40LibABI5858UnwindException41.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/UInt64.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Array40String41.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Int32.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Exception.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/StaticArray40UInt844326541.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/DivisionByZero.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Pointer40String41.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Pointer40Int3241.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Array40Pointer40Void4141.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Pointer40Pointer40Void4141.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Fiber.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Pointer40Void41.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Array40Fiber41.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Pointer40Fiber41.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Event5858Base.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Int64.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Scheduler.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/FileDescriptorIO.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Bool.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/LibEvent25858EventFlags.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Nil.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Errno.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/IO5858Error.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Signal.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/40Int3232456232Void41.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Hash40Int32443240Int3232456232Void4141.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Pointer40Hash40K4-c3ec75a0b68f26d1e6c0b6ef5137591d.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Hash40K4432V41585-f79971827d7c936e8b09d3ee36627c92.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Hash40K4432V415858StandardComparator.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Exception43.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/StaticArray40UInt84432441.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/UInt8.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Amatista5858Handler.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Hash40String4432Array40String4141.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Pointer40Hash40K4-4e22cbfaaeaaecc0f6b9a2d2252636f6.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Array40Amatista5858Route41.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Pointer40Amatista5858Route41.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Array40Amatista5858Filter41.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Pointer40Amatista5858Filter41.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Hash40String4432Hash40String4432String4141.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Pointer40Hash40K4-2a2961ef23c9f44a5615bb37fc51b40e.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Dir.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/HelloWorldController.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Char.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/CharReader.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/InvalidByteSequenceError.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Amatista5858Route.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Mime.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Hash40String4432String41.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Pointer40Hash40K4-94b13ddffb23529372d461c0c2add2fe.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/File.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/123String4432String125.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/File5858Stat.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/JSON.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/JSON5858Parser.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/JSON5858Lexer.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/JSON5858Lexer5858StringBased.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/JSON5858Token.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/StringIO.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/StringPool.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Array40Array40String416341.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Pointer40Array40String416341.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/JSON5858ParseException.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Float64.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Range40B4432E41.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Range40Char4432Char41.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Symbol.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Array40JSON5858Type41.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Pointer40Nil32124-c2dc0208f9353eda20c6cdb68d8d8759.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/StaticArray40UInt844322241.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Hash40String4432JSON5858Type41.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Pointer40Hash40K4-a5f4dccfeeb9e82ab9cf742c0bde63b6.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Hash40K4432V415858Entry40String4432JSON5858Type41.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Hash40K4432V415858Entry40String4432String41.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Hash40Symbol4432Hash40String4432String4141.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Pointer40Hash40K4-d110d9d6a692eac73730424a26c10ac9.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Hash40K4432V41585-7934e7e6ba943faee2108da5e5b4e83a.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/KeyError.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/HTTP5858Headers.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Hash40K4432V41585-6ae11b6ee1fda3db47c9c3f0fe007f56.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/HTTP5858Request.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/PointerAppender40T41.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/PointerAppender40UInt841.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Regex.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Regex5858Options.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/MatchData.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/HTTP5858Response.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Hash40Symbol4432String41.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Pointer40Hash40K4-0e39f657309f762225eca8508214b53b.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Hash40K4432V415858Entry40Symbol4432String41.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Main.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/HTTP5858Server.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Hash40123UInt644432Symbol1254432Bool41.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Pointer40Hash40K4-766bdc6ea432dd2739b30f84312c75af.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/123UInt644432Symbol125.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Hash40K4432V41585-4c57993f23870785eccb6bb4de73a8c0.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Amatista5858Response.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Array40123String4432String12541.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Pointer40123String4432String12541.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Amatista5858Filter.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/CGI.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Array40MatchData41.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Pointer40MatchData41.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/TCPServer.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/SocketError.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/TCPSocket43.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/String5858ToU64Info.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/HTTP5858FixedLengthContent.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/HTTP5858ChunkedContent.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/StaticArray40UInt84432204841.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/HTTP.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/TCPSocket.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/LEBReader.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/Base645858Error.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/ChannelClosed.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/TimeFormat5858Error.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/GlobError.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/IO5858EOFError.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/IO5858Error43.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/DomainError.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/EmptyEnumerable.o" "/Users/olivier/workspace/a_test/.crystal/Users/olivier/workspace/a_test/test.cr/AtExitHandlers.o"   -lssl -levent -lpcl -lpcre -lgc -lpthread`

**Comment by solisoft** [comment]
I wonder if it is related to my mac environment ...

**Comment by solisoft** [comment]
cc -v
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.5.0
Thread model: posix

**Comment by werner** [comment]
I was having that error when I was trying to implement the before callbacks, are you using the last version or changes in amatista?

**Comment by solisoft** [comment]
I just use your code as it

**Comment by werner** [comment]
Weird!, could you please provide me the code so I can do the tests, thanks.

**Comment by solisoft** [comment]
As I said, nothing much, just a basic Projectfile 

```
deps do
   github "spalger/crystal-mime"
   github "werner/amatista"
 end
```

And a basic app (your sample)
    require "amatista"

```
class HelloWorldController < Amatista::Controller
  get "/" do
    html = %(<h1> Hello World </h1>)
    respond_to(:html, html)
  end
end

class Main < Amatista::Base
  configure do |conf|
    conf[:secret_key] = "secret"
    #conf[:logs] = false
  end 
end

app = Main.new
app.run 3000
```

**Comment by werner** [comment]
Try this:

Remove the .deps and libs folder and the .deps.lock file, then run `crystal deps` to update to the latest version, and tell me if you still having the problem.

**Comment by solisoft** [comment]
Same problem ...

**Comment by solisoft** [comment]
Notice that  crystal build amatista.cr --release is working but  crystal build amatista.cr is not

**Comment by werner** [comment]
I don't own a mac, but it looks like crystal needs gmp, libevent and libpcl installed, do you have those?

**Comment by solisoft** [comment]
well, I can run amethyst without issue ...

**Comment by solisoft** [comment]
But I think it's related to my environment though. I'll try to run it on my manjaro linux (If I arrive to run crystal on it :/ )

**Comment by solisoft** [comment]
It's working fine on my linux :+1: so obviously it's a OSX/crystal issue

**Comment by werner** [comment]
Ok, glad to know at least works on linux.
